# This is a basic workflow to help you get started with Actions

name: Continuous integration & deployment workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

